name:                servant-to-elm
version:             0.1.0.0
github:              "folq/servant-to-elm"
license:             BSD3
author:              "Olle Fredriksson"
maintainer:          "fredriksson.olle@gmail.com"
copyright:           "2019 Olle Fredriksson"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Automatically generate Elm clients for Servant APIs
category:            Servant, API, Elm, Compiler

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/folq/servant-to-elm#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bound
- elm-syntax
- haskell-to-elm
- http-types
- protolude
- servant
- text

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wtabs
  - -funbox-strict-fields

library:
  source-dirs: src

tests:
  servant-to-elm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-to-elm

flags:
  examples:
    description: Build examples
    manual: true
    default: false

executables:
  user-example:
    source-dirs: examples
    main: UserAPI.hs
    dependencies:
      - generics-sop
      - servant
      - servant-to-elm
      - unordered-containers
    when:
      condition: "!flag(examples)"
      buildable: false
